import { AuditReport } from "@/lib/api";

type AIAuditSummaryProps = {
  report: AuditReport;
};

export function AIAuditSummary({ report }: AIAuditSummaryProps) {
  const hasContent =
    report.ai_summary || report.ai_business_risk || report.ai_recommendations.length > 0;

  if (!hasContent) return null;

  const isAI = report.ai_provider === "openai";

  return (
    <section className="mt-8 rounded-2xl border border-indigo-500/30 bg-gradient-to-br from-indigo-950/40 to-zinc-900/50 p-8">
      <div className="flex items-center gap-3">
        <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-500/20 text-lg">
          🤖
        </span>
        <div>
          <h2 className="text-lg font-semibold text-zinc-50">AI Auditor Assessment</h2>
          <p className="text-xs text-zinc-400">
            {isAI
              ? "Generated by AI from your audit findings"
              : "Generated by the built-in rule-based auditor"}
          </p>
        </div>
        <span
          className={`ml-auto rounded-full px-3 py-1 text-xs font-medium ${
            isAI
              ? "bg-indigo-500/20 text-indigo-300"
              : "bg-zinc-700/40 text-zinc-300"
          }`}
        >
          {isAI ? "AI-powered" : "Rule-based"}
        </span>
      </div>

      {report.ai_summary && (
        <Block title="Executive Summary">
          <p className="text-sm leading-relaxed text-zinc-200">{report.ai_summary}</p>
        </Block>
      )}

      {report.ai_business_risk && (
        <Block title="Business Risk">
          <p className="text-sm leading-relaxed text-amber-200">{report.ai_business_risk}</p>
        </Block>
      )}

      {report.ai_recommendations.length > 0 && (
        <Block title="Strategic Recommendations">
          <ul className="space-y-2">
            {report.ai_recommendations.map((rec, index) => (
              <li
                key={index}
                className="flex gap-3 rounded-lg border border-zinc-800 bg-zinc-950/40 px-4 py-3 text-sm text-zinc-300"
              >
                <span className="font-semibold text-indigo-400">{index + 1}.</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </Block>
      )}
    </section>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-6">
      <h3 className="mb-2 text-xs font-medium uppercase tracking-widest text-zinc-500">
        {title}
      </h3>
      {children}
    </div>
  );
}
