"""Professional PDF audit report export."""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.schemas.scan import AuditReportResponse


def generate_audit_pdf(report: AuditReportResponse, project_name: str = "Project") -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=20,
        spaceAfter=12,
        textColor=colors.HexColor("#10b981"),
    )
    heading = styles["Heading2"]
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=body, fontSize=9, textColor=colors.grey)

    story: list = []
    story.append(Paragraph("AI Software Auditor — Audit Report", title_style))
    story.append(Paragraph(f"Project: <b>{project_name}</b>", body))
    story.append(
        Paragraph(
            f"Overall Health Score: <b>{report.overall_score}/100</b> "
            f"(Grade {report.grade}) — "
            f"{'Production Ready' if report.production_ready else 'Not Production Ready'}",
            body,
        )
    )
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Executive Summary", heading))
    story.append(Paragraph(report.executive_summary, body))
    story.append(Spacer(1, 0.15 * inch))

    if report.ai_summary:
        story.append(Paragraph("AI Auditor Assessment", heading))
        story.append(Paragraph(report.ai_summary, body))
        if report.ai_business_risk:
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(f"<b>Business Risk:</b> {report.ai_business_risk}", body))
        story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("Category Breakdown", heading))
    cat_data = [["Category", "Score", "Issues"]]
    for cat in report.categories:
        cat_data.append([cat.category.title(), str(cat.score), str(cat.issue_count)])
    cat_table = Table(cat_data, colWidths=[2.5 * inch, 1.2 * inch, 1.2 * inch])
    cat_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#27272a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f4f5")]),
            ]
        )
    )
    story.append(cat_table)
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Severity Breakdown", heading))
    sev = report.severity_breakdown
    story.append(
        Paragraph(
            f"Critical: {sev.get('critical', 0)} · High: {sev.get('high', 0)} · "
            f"Medium: {sev.get('medium', 0)} · Low: {sev.get('low', 0)}",
            body,
        )
    )
    story.append(Spacer(1, 0.15 * inch))

    if report.fix_plan:
        story.append(Paragraph("Recommended Fix Order", heading))
        for step in report.fix_plan:
            story.append(Paragraph(step, body))
            story.append(Spacer(1, 0.08 * inch))

    if report.top_priority_issues:
        story.append(Paragraph("Top Priority Issues", heading))
        for issue in report.top_priority_issues[:8]:
            story.append(
                Paragraph(
                    f"<b>[{issue.severity.upper()}]</b> {issue.title}",
                    body,
                )
            )
            story.append(Paragraph(issue.fix_recommendation, small))
            story.append(Spacer(1, 0.1 * inch))

    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            "Generated by AI Software Auditor — Problem → Impact → Business Risk → Fix → Priority",
            small,
        )
    )

    doc.build(story)
    return buffer.getvalue()
